/**
 * Builds the browser bundle.
 *
 * The Client half must arrive as one lazily-required bundle whose factory id is
 * the package name, so the modules under `src/` are concatenated in dependency
 * order into `client.js`. The build is deliberately dependency-free and fails
 * loudly on a stray import/export, a duplicate top-level name, or an asset that
 * carries anything executable.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8');

/** Concatenation order must satisfy every module's imports. */
const MODULES = [
  'src/prefs.js',
  'src/i18n.js',
  'src/segments.js',
  'src/usage.js',
  'src/balance.js',
  'src/view.js',
  'src/account.js',
  'src/widget.js',
  'src/controller.js',
  'src/adapter.js',
];

/** Only a static, non-interactive, self-contained SVG may enter the shadow root. */
export function validateSvg(source, name) {
  // Comments are inert and dropped so the emitted asset carries markup only.
  const markup = source.replace(/<!--[\s\S]*?-->/g, '').trim();
  if (!/^<svg\s/.test(markup)) throw new Error(`Unsafe SVG (${name}): must start with <svg`);
  if (/<!|<\?|\bon\w+\s*=|\bhref\s*=|<script|<foreignObject|\bstyle\s*=|javascript:|data:|url\(/i.test(markup)) {
    throw new Error(`Unsafe SVG (${name}): contains scriptable or external content`);
  }
  const tags = [...markup.matchAll(/<\/?([a-zA-Z][\w:-]*)\b/g)].map(match => match[1].toLowerCase());
  const allowed = new Set(['svg', 'g', 'path', 'rect', 'circle', 'ellipse', 'line', 'polyline', 'polygon', 'defs', 'linearGradient', 'radialGradient', 'stop', 'title', 'desc']);
  for (const tag of tags) if (!allowed.has(tag)) throw new Error(`Unexpected SVG element (${name}): <${tag}>`);
  if (!/viewBox="[\d.\s-]+"/.test(markup)) throw new Error(`Missing viewBox (${name})`);
  if (!/xmlns=/.test(markup)) throw new Error(`Missing xmlns (${name})`);
  return markup;
}

/** Strip the module boundary: only the leading `import` and `export` keywords go. */
export function toBundleScope(source, name) {
  const stripped = source
    .replace(/^import\s[^\n]*;\s*$/gm, '')
    .replace(/^export\s+(?=(?:async\s+)?(?:function|class|const|let|var)\b)/gm, '');
  const leftover = stripped.match(/^\s*(?:import|export)\b/gm);
  if (leftover !== null) throw new Error(`Module ${name} still carries ${leftover.length} import/export statement(s); the bundler only inlines named declarations`);
  return stripped;
}

const DECLARATION = /^(?:async\s+)?(?:function|class)\s+([A-Za-z_$][\w$]*)|^(?:const|let|var)\s+([A-Za-z_$][\w$]*)/gm;

/** Concatenated modules share one scope, so a repeated top-level name would silently rebind. */
export function findDuplicateDeclarations(scopes) {
  const seen = new Map();
  const duplicates = [];
  for (const { name, source } of scopes) {
    for (const match of source.matchAll(DECLARATION)) {
      const identifier = match[1] ?? match[2];
      const owner = seen.get(identifier);
      if (owner === undefined) seen.set(identifier, name);
      else duplicates.push(`${identifier} (${owner} and ${name})`);
    }
  }
  return duplicates;
}

export function buildBundle({ pkg, scopes, assets, css }) {
  const duplicates = findDuplicateDeclarations(scopes);
  if (duplicates.length > 0) throw new Error(`Duplicate top-level declarations in the bundle: ${duplicates.join(', ')}`);
  return `// Generated by tools/build.mjs from src/ — do not edit by hand.
window.__ModuleLoader__.load({
  id: ${JSON.stringify(pkg.name)},
  factory: function (require) {
    'use strict';
    const ASSETS = ${JSON.stringify(assets)};
    const CSS = ${JSON.stringify(css)};
${scopes.map(scope => scope.source).join('\n')}
    return createPlugin(require, ASSETS, CSS);
  },
});
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const pkg = JSON.parse(read('package.json'));
  const assets = { unit: validateSvg(read('assets/unit.svg'), 'unit.svg') };
  const css = read('src/hud.css');
  const scopes = MODULES.map(name => ({ name, source: toBundleScope(read(name), name) }));
  const bundle = buildBundle({ pkg, scopes, assets, css });
  const required = ['window.__ModuleLoader__', `id: ${JSON.stringify(pkg.name)}`, 'return createPlugin(require, ASSETS, CSS);'];
  for (const token of required) if (!bundle.includes(token)) throw new Error(`Bundle is missing ${token}`);
  fs.writeFileSync(path.join(root, 'client.js'), bundle);
  console.log(`Built client.js from ${MODULES.length} modules; validated assets/unit.svg (${assets.unit.length} bytes).`);
}
